models:
  llama3-2:
    model: ai/llama3.2:3B-F16
  # qwen2-5-coder:
  #   model: hf.co/Qwen/Qwen2.5-Coder-7B

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main-slim
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:12434
      - WEBUI_AUTH=false
      # If you prefer to use the OpenAI-compatible API instead of the Ollama API, set the following environment variable:
      - OPENAI_API_KEY=not-needed
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    models:
      - llama3-2
      # - qwen2-5-coder

volumes:
  open-webui:
